app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: /
    defaults:
      _controller: FrameworkBundle:Template:template

#container routing
#lucky_number:
#  path: /lucky/number/{count}
#  defaults: {_controller: AppBundle:Lucky:number}

#service route
lucky_number:
  path: /lucky/number/{count}
  defaults: {_controller: app.lucky_controller:numberAction}