#lesen aller Routing Annotations im ControllerDirectory
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

hello:
    resource: "hello_routing.yml"
    prefix: /hello

blog:
    resource: "blog_routing.yml"
    prefix: /blog

home:
    path: /
    defaults:
      _controller: FrameworkBundle:Template:template

#container routing
#lucky_number:
#  path: /lucky/number/{count}
#  defaults: {_controller: AppBundle:Lucky:number}

#service route
lucky_number:
  path: /lucky/number/{count}
  defaults: {_controller: app.lucky_controller:numberAction}
